### ISSUE TITLE
Add support for Euros €

### ISSUE THREAD

**Issue by edoz90** [miguelmota/cointop#10]
From the API is possibile to select a different currency: https://api.coinmarketcap.com/v2/ticker/?convert=EUR&limit=10

**Comment by miguelmota** [comment]
@edoz90 added currency convert support

Delete your config 

```
rm ~/.cointop
```

or update it to use the action `show_currency_convert_menu` on `c` key press.

```
c = "show_currency_convert_menu"
```

When you press <kbd>c</kbd> it'll bring up a menu like this

<img width="984" alt="screen shot 2018-05-07 at 12 53 04 am" src="https://user-images.githubusercontent.com/168240/39691203-9bf48c16-5191-11e8-9207-8e3d9f7b33f5.png">
