### ISSUE TITLE
Docker - SSH key is required to start server

### ISSUE THREAD

**Issue by skiwithpete** [miguelmota/cointop#100]
Hi, 

I'm trying to run cointop on docker.  But I can't seem to get it to run.  Instead I get an error "SSH key is required to start server"

```
docker run -p 2222:2222 -v ~/.ssh:/keys --entrypoint cointop -it cointop/cointop server -k /keys/id_rsa
Running SSH server on port 22
Error: SSH key is required to start server
Usage:
  cointop server [flags]

Flags:
  -a, --address string         Address (default "0.0.0.0")
  -b, --binary string          Executable binary path (default "cointop")
  -h, --help                   help for server
  -k, --host-key-file string   Host key file (default "~/.ssh/id_rsa")
  -t, --idle-timeout uint      Idle timeout in seconds. Default is 0 for no idle timeout
      --max-sessions uint      Max number of sessions allowed. Default is 0 for unlimited.
  -m, --max-timeout uint       Max timeout in seconds. Default is 0 for no max timeout
  -p, --port uint              Port (default 22)

SSH key is required to start server
```

**Comment by miguelmota** [comment]
To run cointop app:

```bash
docker run -it cointop/cointop
```

To run cointop SSH server:

1. Generate SSH key if you don't have one
    ```bash
   $ ssh-keygen
   ```
2. Check keys were generated:
    ```bash
    $ ls ~/.ssh
    id_rsa id_rsa.pub
    ```

3. Run docker cointop server:
    ```bash
    docker run -p 2222:22 -v ~/.ssh:/keys --entrypoint cointop -it cointop/cointop server -k /keys/id_rsa
    ```

4. Connect:
    ```bash
   ssh localhost -p 2222
   ```

**Comment by skiwithpete** [comment]
Thank you.  How do I make my portfolio and settings persistent?

**Comment by miguelmota** [comment]
Good question; cointop server currently writes the connecting client config to `/tmp/cointop_config` within the container, so to make it persistent attach a volume:

```bash
-v ~/.cache/cointop:/tmp/cointop_config
```

Full command:

```bash
docker run -p 2222:22 -v ~/.ssh/demo:/keys -v ~/.cache/cointop:/tmp/cointop_config --entrypoint cointop -it cointop/cointop server -k /keys/id_rsa
```

It'll write the cached config to `~/.cache/cointop` on the host.

**Comment by skiwithpete** [comment]
I'm doing it in Portainer, so I see it all graphically.

Host/volume | Path in container
/media/1tb/configs/cointop | /tmp/cointop_config

I also chmod'd to 777 the host volume.

But nothing populates in that directory.  I also used the ctrl+s command to try to save favorites, and it didn't appear to write anything, and saves were not made.

is there something else I can try?

**Comment by miguelmota** [comment]
If you're running cointop app (not server) then config is under `/root/.config/cointop` in container:

```bash
docker run -v ~/.cache/cointop:/root/.config/cointop -it cointop/cointop
```

In this example, config will be populated under `~/.cache/cointop/config.toml` in host.

I'm on a linux machine and attaching the volume like in the above example works as expected. I haven't used Portainer before but I'll check it out and see if I can get it working with it!

**Comment by skiwithpete** [comment]
portainer is just a graphical interface for docker.

But when I attach /root/.config/cointop I still don't see my host volume populate with anything.

Because i'm running the container, I'm not sure if I'm running server or the app.

**Comment by miguelmota** [comment]
Do you have an SSH key on the remote machine and are you using the same key every time? the public key fingerprint is used for mapping the config file to user.

I download and ran portainer, and was able to hook it up successfully.

In order to persist to local disk, I used [local-persist](https://github.com/MatchbookLab/local-persist). 

To install local-persist:

```bash
curl -fsSL https://raw.githubusercontent.com/MatchbookLab/local-persist/master/scripts/install.sh | sudo bash
```

Then restart portainer.

My volume config was the following (your path username will be different):

![DeepinScreenshot_select-area_20210326150046](https://user-images.githubusercontent.com/168240/112697849-b0800680-8e45-11eb-8255-de10eea73e8a.png)


![DeepinScreenshot_select-area_20210326150821](https://user-images.githubusercontent.com/168240/112697834-a78f3500-8e45-11eb-9a90-8aa56f84d0e3.png)


![DeepinScreenshot_select-area_20210326150900](https://user-images.githubusercontent.com/168240/112697820-a3631780-8e45-11eb-8430-4824e03cf83e.png)

My command config was the following:

![DeepinScreenshot_select-area_20210326150144](https://user-images.githubusercontent.com/168240/112697940-d2798900-8e45-11eb-923c-6d8a101ede7b.png)

Afterwards I was able to connect to the local IP portainer gives you:

```
ssh 172.17.0.3
```

And config on host should be in the path specified for volume value.

**Comment by skiwithpete** [comment]
<img width="961" alt="Screen Shot 2021-03-26 at 7 54 19 PM" src="https://user-images.githubusercontent.com/10486285/112703373-1a5fd680-8e6d-11eb-9dc8-f408c1577eba.png">

<img width="337" alt="Screen Shot 2021-03-26 at 7 55 00 PM" src="https://user-images.githubusercontent.com/10486285/112703413-319ec400-8e6d-11eb-84d0-a60ffbcebdde.png">

When I press e and then enter a value, shift+p and go to my portfolio view.  Then ctrl+s.  It does not save.  When I log back in, values are lost.  When I look at the now persistent folder, it is empty.  No configuration is saved.

**Comment by miguelmota** [comment]
The screenshot config looks correct. Can you share the volume config showing the driver options?

**Comment by skiwithpete** [comment]
<img width="956" alt="Screen Shot 2021-03-27 at 10 29 09 AM" src="https://user-images.githubusercontent.com/10486285/112723962-694a5200-8ee7-11eb-813d-4193ebbe171d.png">

<img width="363" alt="Screen Shot 2021-03-27 at 10 43 39 AM" src="https://user-images.githubusercontent.com/10486285/112724362-59cc0880-8ee9-11eb-9d01-b8bcc0655477.png">

Do you want to see for SSH too?

**Comment by miguelmota** [comment]
All that looks right. Can you try entering into the container and seeing if the files exist there?

```
$ docker exec -it <container-id> sh
/ # ls -l /tmp/cointop_config/
```

Example

![DeepinScreenshot_select-area_20210327125942](https://user-images.githubusercontent.com/168240/112733312-7f164200-8efc-11eb-8a94-6de4e6732617.png)

**Comment by skiwithpete** [comment]
<img width="726" alt="Screen Shot 2021-03-27 at 5 09 05 PM" src="https://user-images.githubusercontent.com/10486285/112734943-3b80ff80-8f1f-11eb-970d-804bb40893ca.png">

Then, just to check it was working.  I dragged a file from my desktop into the folder, just to see if it would appear...  it did.

<img width="724" alt="Screen Shot 2021-03-27 at 5 10 47 PM" src="https://user-images.githubusercontent.com/10486285/112734969-7a16ba00-8f1f-11eb-881c-1df6ea0abe3e.png">

**Comment by miguelmota** [comment]
Interesting, this is what I'm seeing:

![Peek 2021-03-27 20-29](https://user-images.githubusercontent.com/168240/112741491-303bcd00-8f3b-11eb-822f-2c28f962f304.gif)

The remote client machine has SSH keys under ~/.ssh correct?

**Comment by miguelmota** [comment]
Example of docker run command and persistent config after connecting with SSH:

![Peek 2021-03-27 20-45](https://user-images.githubusercontent.com/168240/112741781-60846b00-8f3d-11eb-9042-46ecbd6e88cb.gif)

**Comment by skiwithpete** [comment]
I'm connecting with a MacBook and a Raspberry pi, so both remote machines are under ~/.ssh.  

I notice you're doing your demo over localhost.  So I did it over localhost as well, and look:

<img width="573" alt="Screen Shot 2021-03-27 at 11 53 05 PM" src="https://user-images.githubusercontent.com/10486285/112741923-c5e55580-8f57-11eb-8a0e-5af3bf9fe62a.png">

BUT, when I did it, not over localhost, just elsewhere in the network.  It did not write.  

I also did it on the demo site with ssh cointop.sh - and this did not save my preferences either.  Do you have a second machine that you can use the SSH into your host and test?

**Comment by miguelmota** [comment]
This example is connecting to a raspberry pi on a different IP:

![Peek 2021-03-27 23-12](https://user-images.githubusercontent.com/168240/112744123-03df7b00-8f52-11eb-9ab7-91923ad28cf9.gif)

What's the SSH command you're using to connect? is it using password or public key?

**Comment by skiwithpete** [comment]
<img width="662" alt="Screen Shot 2021-03-28 at 9 05 46 AM" src="https://user-images.githubusercontent.com/10486285/112753269-ebe51700-8fa4-11eb-9de4-5a539acb3d37.png">

When I ran ssh-keygen, I did so without entering a password, as this is all on my local home network.

**Comment by skiwithpete** [comment]
https://user-images.githubusercontent.com/10486285/112769806-0ba22c80-8ff1-11eb-9cb6-0566709a49b7.mp4

**Comment by miguelmota** [comment]
@skiwithpete thanks for the video. Can you try this info server `ssh whoami.filippo.io` and let me know if shows your public key or not?

**Comment by skiwithpete** [comment]
<img width="486" alt="Screen Shot 2021-03-29 at 9 48 27 AM" src="https://user-images.githubusercontent.com/10486285/112846416-076b2300-9074-11eb-9e1c-61f76578e64a.png">

Unable to connect

**Comment by skiwithpete** [comment]
ssh whoami.filippo.io
Connection closed by 108.30.214.28 port 22

and

ssh whoami.filippo.io -p 2222
ssh: connect to host whoami.filippo.io port 2222: Connection refused

**Comment by miguelmota** [comment]
Going to make some adjustments in the server code which should guarantee that a config is always generated since it's been difficult debugging this particular issue. I'll keep you updated here when the changes are made : )

**Comment by skiwithpete** [comment]
It would be cool if I could make changes at one point and have it reflect
across the entire network.

For example, if I change it on localhost, then no matter which computer I
log into on, I always have the same favorites, and portfolio.

Just sayin.

**Comment by miguelmota** [comment]
@skiwithpete There's an option now available to use the client username as the identifier instead of client's SSH public key by using the `--user-config-type=username` option.

Pull latest:

```bash
docker pull cointop/cointop
```

Full command:

```bash
docker run -p 2222:22 -v ~/.ssh:/keys -v ~/.cache/cointop:/tmp/cointop_config --entrypoint cointop -it cointop/cointop server -k /keys/id_rsa --user-config-type=username
```

SSH'ing with username will generate and persist the user's respective config based on username:

```bash
ssh alice@host -p 2222 
ssh bob@host -p 2222
```

Let me know if this works for you!

Regarding the user config being available on any machine; it's definitely a cool idea but it would require storing user config in a central server so it can always pull and update their config from where ever they log in from. Maybe in the future cointop can have user authentication for this feature.

**Comment by skiwithpete** [comment]
Awesome, thanks!
