### ISSUE TITLE
Portfolio charting broken

### ISSUE THREAD

**Issue by skiwithpete** [miguelmota/cointop#103]
<img width="557" alt="Screen Shot 2021-04-06 at 11 07 47 PM" src="https://user-images.githubusercontent.com/10486285/113804635-f7ff7000-972c-11eb-89e8-3e1c3291deb4.png">

Inside portfolio, choosing different views breaks the charting.

This is not my real portfolio, I tried this with various portfolio sizes and scales, and all were broken.

**Comment by YoannPa** [comment]
> <img alt="Screen Shot 2021-04-06 at 11 07 47 PM" width="557" src="https://user-images.githubusercontent.com/10486285/113804635-f7ff7000-972c-11eb-89e8-3e1c3291deb4.png">
> 
> Inside portfolio, choosing different views breaks the charting.
> 
> This is not my real portfolio, I tried this with various portfolio sizes and scales, and all were broken.

+1 : same issue here for me.

**Comment by simon-anz** [comment]
Duplicate of #108

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/pull/137
