### ISSUE TITLE
Custom path to config does not work

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [miguelmota/cointop#106]
Hello, first off, thanks for the project!

I got a bug. Let's say I have two config fils:

```
$ ls ~/.config/cointop
config1.toml
config2.toml
```

Below will work fine

```
$ cointop -c $HOME/.config/cointop/config1.toml
```

Below will also work fine

```
$ cointop -c $HOME/.config/cointop/config2.toml
```

However, after creating a file called config.toml, it no longer works.

```
$ cp ~/.config/cointop/config1.toml ~/.config/cointop/config.toml
$ cointop -c $HOME/.config/cointop/config2.toml # this does not work.
```

In line above cointop will use the file `config.toml` instead of `config2.toml`

If I have a file in `~/.config/cointop/config.toml`, then this config file will override any config file passed as a command line argument.

For example, my `config.toml` shows the default columns and `config2.toml` shows only a few columns. I can't use the config from `config2.toml` if `~/.config/cointop/config.toml` exists. To be able to have multiple config files it is needed to delete the file `~/.config/cointop/config.toml` and use the `-c` flag every time `cointop` is run.

I guess this behavior should not happen.

**Comment by miguelmota** [comment]
Hi @AndreSouzaAbreu! 

The config file path issue is now fixed in the main branch. Going to push new releases soon.

Thanks!

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/e0acaf9554c7c92133c952aef63fb72cf2990c1d
