### ISSUE TITLE
Getting Portfolio total only over SSH

### ISSUE THREAD

**Issue by skiwithpete** [miguelmota/cointop#107]
Hi,

I want to build a Raspberry Pi project with an e-ink screen that displays only the total of my portfolio.

I noticed that cointop allows for a -c call.

I was wondering if there was a way to do that -c call for my portfolio.  While SSH'ing into a docker.

+ as a little addon to the question, will it hold the connection or just check in an instant and then close the SSH?

**Comment by miguelmota** [comment]
@skiwithpete 

You can try something like this

```
$ docker exec -it <container-id> sh
# cointop holdings --total --config /tmp/cointop_config/<config-id>/config
```

or

```
$ docker exec -it <container-id> cointop holdings --total --config /tmp/cointop_config/<config-id>/config
```

**Comment by miguelmota** [comment]
@skiwithpete 

To query over the SSH server, try this with latest code on main branch:

```bash
$ ssh localhost -p 2222 -q -t holdings --total
100.1
```

The connection will close immediately, but you can use something like the `watch` command to constantly poll:

```bash
watch -tn1 ssh localhost -p 2222 -q -t holdings --total
```

**Comment by skiwithpete** [comment]
I get this error message:



$ ssh ***@***.*** -p 2222 -q -t holdings --total

Error: unknown flag: --total

Usage:

  cointop [flags]

  cointop [command]


Available Commands:

  clean       Clear the cache

  dominance   Displays bitcoin dominance

  help        Help about any command

  holdings    Displays current holdings

  price       Displays the current price of coin(s)

  reset       Resets the config and clear the cache

  server      Run cointop SSH Server

  test        Runs tests for Homebrew

  version     Displays the current version


Flags:

      --api string                     API choice. Available choices are
"coinmarketcap" and "coingecko"

      --cache-dir string               Cache directory (default /tmp)

      --clean                          Wipe clean the cache

      --coinmarketcap-api-key string   Set the CoinMarketCap API key

      --colors-dir string              Colorschemes directory

      --colorscheme string             Colorscheme to use (default
"cointop").

                                       To install standard themes, do:



                                       git clone
***@***.***:cointop-sh/colors.git
~/.config/cointop/colors



                                       See git.io/cointop#colorschemes for
more info.

  -c, --config string                  Config filepath. (default
~/.config/cointop/config.toml)

  -h, --help                           help for cointop

      --hide-chart                     Hide the chart view

      --hide-marketbar                 Hide the top marketbar

      --hide-statusbar                 Hide the bottom statusbar

      --max-pages uint                 Max number of pages (default 35)

      --no-cache                       No cache

      --only-table                     Show only the table. Hides the chart
and top and bottom bars

      --per-page uint                  Per page (default 100)

  -r, --refresh-rate uint              Refresh rate in seconds. Set to 0 to
not auto-refresh (default 60)

      --reset                          Reset the config. Make sure to
backup any relevant changes first!

  -s, --silent                         Silence log ouput

      --test                           Run test (for Homebrew)

  -v, --version                        Display current version


Use "cointop [command] --help" for more information about a command.


unknown flag: --total

**Comment by miguelmota** [comment]
@miguelmota try updating docker image and re-running ssh server

```bash
docker pull cointop/cointop
```

**Comment by skiwithpete** [comment]
worked.

The only problem is it's a way smaller number than it was last week ;)

Thanks for this program and all your help.

**Comment by miguelmota** [comment]
@skiwithpete awesome! 

yeah, hopefully the chart goes 📈 soon and then 🚀 to the  🌕 

: )
