### ISSUE TITLE
Portfolio chart is totally wrong 

### ISSUE THREAD

**Issue by ronki2304** [miguelmota/cointop#108]
Hello,

I have issue with the portfolio chart, what it displays does not have any sense

![image](https://user-images.githubusercontent.com/25466164/115106989-67186800-9f68-11eb-9bc0-a2204e9777eb.png)

I am using ubuntu 20.04 
![image](https://user-images.githubusercontent.com/25466164/115106960-2e788e80-9f68-11eb-89ce-74fbad3d5c0a.png)

do i need to setup something?

**Comment by calgara12** [comment]
I have the same problem, using the docker image

**Comment by simon-anz** [comment]
I have same issue, using latest code.

**Comment by simon-anz** [comment]
![Screen Shot 2021-08-18 at 8 37 23 am](https://user-images.githubusercontent.com/69175652/129809848-11a3e394-7613-4e5c-9a1d-68c2683d0b34.png)

**Comment by simon-anz** [comment]
It looks like when it's collecting portfolio data, it's not correctly aggregating.  Trying to debug now, but I really don't know golang! :)

**Comment by simon-anz** [comment]
Issues:

1.  not all the coins have the same amount of data (maybe some coins are too young?). In my data set
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from btc_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from ada_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from eth_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from bch_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 98 items from xrp_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from xlm_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from matic_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 87 items from eos_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from algo_1y
2021/08/18 11:10:16 PortfolioChart() ===> adding 337 items from ltc_1y

2. the data[] that the graph is drawn from is actually an *appended* list of holdings*price for each asset in the portfolio.  So the left hand set of points is BTC portfolio-value, the next bit is ADA, etc

**Comment by simon-anz** [comment]
eg: with a portfolio of 1 BTC and 1 ETH, the graph looks like
![Screen Shot 2021-08-18 at 11 19 13 am](https://user-images.githubusercontent.com/69175652/129821252-fc90b93e-7989-451a-bd20-e527bdff3653.png)

**Comment by simon-anz** [comment]
I think problem is that the aggregator is appending the value item to the data set, even when it should be _adding_ it.
```
$ git diff cointop/chart.go
diff --git a/cointop/chart.go b/cointop/chart.go
index a566b75..81f7d09 100644
--- a/cointop/chart.go
+++ b/cointop/chart.go
@@ -256,10 +256,11 @@ func (ct *Cointop) PortfolioChart() error {
                for i := range graphData {
                        price := graphData[i]
                        sum := p.Holdings * price
-                       if len(data)-1 >= i {
+                       if i < len(data) {
                                data[i] += sum
+                       } else {
+                               data = append(data, sum)
                        }
-                       data = append(data, sum)
                }
        }
```

This produces far more sensible graphs

![Screen Shot 2021-08-18 at 11 41 28 am](https://user-images.githubusercontent.com/69175652/129823076-04f4e816-8d7d-4da9-bb0c-62f353550e43.png)
![Screen Shot 2021-08-18 at 11 41 39 am](https://user-images.githubusercontent.com/69175652/129823091-d83c561f-f5db-4e6d-bbef-e354bedde358.png)

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/pull/137
