### ISSUE TITLE
Allow simple calculations when editing portfolio entries

### ISSUE THREAD

**Issue by vatonbero** [miguelmota/cointop#110]
Hi,

When you add some values to your portfolio, it would help a lot to allow us to use basic addition and subtraction operations when we edit some entries.

My idea is quite simple
- you open cointop
- open [__P__]ortfolio
- select desired cryptocurrency and [__E__]dit it
- Instead of pre-calcualtions in some other place (desktop calculator, handheld one or any other way), you just type something like `1.001+0.981918167` and hit Enter
- cointop calculates numbers from the input and displays new value

**Comment by simon-anz** [comment]
I think we can close this now: the portfolio entry now supports entering expressions, and even takes the currently selected coin as context, so you can use `1000/Price` to work out how many units you bought for $1000, or `Holdings*2` to double your position.  See #154

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/pull/154
