### ISSUE TITLE
Get portfolio value by calling cointop with a flag/command

### ISSUE THREAD

**Issue by vatonbero** [miguelmota/cointop#111]
Hi there,

Is there a chance to consider adding command for getting current portfolio value? We could use that for piping the results and further manipulate them.

Something like: `cointop portfolio-value` shich would print something like
```
Total Portfolio Value: $1.001
24H: -10.01%
```
Important to know and nice to have:
- Do not show any ascii chars and use only plaintext
- Separate values into rows so we could minimize the number of tools used for manipulation. In above example, you could get details by using `cointop portfolio-value | tail -1` and you would get something like `24H: -10.01%`

**Comment by miguelmota** [comment]
@vatonbero check out [docs.cointop.sh/portfolio/#cli](https://docs.cointop.sh/portfolio/#cli)

A few examples:

```bash
$ cointop holdings
    name        symbol       price      holdings         balance         24h%   %holdings
Bitcoin         BTC       11833.16            10        118331.6        -1.02       74.14
Ethereum        ETH          394.9           100           39490         0.02       24.74
Dogecoin        DOGE    0.00355861        500000          1779.3         1.46        1.11
```

```bash
$ cointop holdings --total
3671.32
```

```bash
$ cointop holdings --cols=24h% -h --no-header
  24h% 
-1.02%
 0.02%
 1.46%
```

**Comment by vatonbero** [comment]
I might be wrong but `--cols` is not available? I get the following:
```
unknown flag: --cols
```

**Comment by miguelmota** [comment]
@vatonbero it's on the main branch, so you'll see it if you compile from source or install with go get.  New releases will be published soon.

**Comment by vatonbero** [comment]
Roger that, let us leave this issue opened until next release to test the functionality live.

**Comment by skiwithpete** [comment]
How can this be done with SSH into the docker?

**Comment by miguelmota** [comment]
@skiwithpete 

```
$ docker exec -it <container-id> sh
# cointop holdings --config /tmp/cointop_config/<config-id>/config
```

or

```
$ docker exec -it <container-id> cointop holdings --config /tmp/cointop_config/<config-id>/config
```

**Comment by vatonbero** [comment]
Hi there. This works as intended but i cannot understand if i am missing something or if there is no way to display total portfolio change in the past 24h? You can get total value of your portfolio however you cannot get that digit displayed on `cointop` from header where it states summarized portfolio change in the past 24h.

**Comment by miguelmota** [comment]
@vatonbero ah i see, I misunderstood the question. There currently isn't a way but should be easy to add. Will post here when it's available.

**Comment by miguelmota** [comment]
@vatonbero the `--24h` flag has been added to return 24H% percent change of total holdings

```bash
$ cointop holdings --24h
-3.03
```
