### ISSUE TITLE
Flatpak package is out of date compared to recent commits and releases

### ISSUE THREAD

**Issue by cmosetick** [miguelmota/cointop#124]
Flathub git repository commit message says from March 22 on commit 8c82da8:
> Update to v1.6.3

However, version v1.4.5 is what is listed in flathub repository via search command and web site right now:

```
flatpak search cointop

Name   Version Branch Remotes
Cointop  1.4.5   stable flathub
```

Reference:
https://github.com/flathub/com.github.miguelmota.Cointop/commit/8c82da891febe497e9d6f0ed020fe3ec25d58c8b

**Comment by miguelmota** [comment]
@cmosetick great catch! A patch as been [submitted](https://github.com/flathub/com.github.miguelmota.Cointop/commit/aa8651ba5f7142266f598ae62b440b6b43757dc7) and flathub should update the version any minute now after it builds

**Comment by miguelmota** [comment]
It is update-to-date now

```bash
$flatpak search cointop
Name              Description                                                        Application ID                          Version           Branch          Remotes
Cointop           Terminal based application for tracking cryptocurrencies           com.github.miguelmota.Cointop           1.6.5             stable          flathub
```

**Comment by cmosetick** [comment]
Thanks for the Flatpak update!
I just wanted to let you know that on some Linux systems, `cointop` only appears in the program launcher menu. It does not show up in the PATH of my system/user account. I think this is likely because of how my system is setup with respect to Flatpak. As Flatpak seems to focus much more on bulky GUI applications than CLI apps.

Also, FYI - when I launch `cointop` from the Cinnamon graphical program launcher it opens up a standard terminal to launch cointop as I would expect. But it does not read my local `config.toml` file that I have set in my `.zshrc` file:

`export COINTOP_CONFIG="$HOME/.config/cointop/config.toml"`
It seems likely that the flatpak installed version has an issue because of the user that is launched as, but just a guess.

I also tested a new Linux Homebrew install and it seems to be working great.
The Homebrew installed version **does** read/use this config file variable correctly.

Info regarding the Flatpak installed version is here, for anyone else that notices the same issue regarding PATH:
```
➜  ~ ls -lah /var/lib/flatpak/app/com.github.miguelmota.Cointop/x86_64/stable/925c0d650c53b0eeb41b68e43c96fca582538b83aea6297246a9d08ae073741c/files/bin/cointop
-rwxr-xr-x 2 root root 9.9M May  4 15:04 

➜  ~ /var/lib/flatpak/app/com.github.miguelmota.Cointop/x86_64/stable/925c0d650c53b0eeb41b68e43c96fca582538b83aea6297246a9d08ae073741c/files/bin/cointop --version
v1.6.5
```

**Comment by miguelmota** [comment]
@cmosetick Thanks for bringing this up! Since flatpak sandboxes the programs, we must give it permission to the host filesystem. Also the $HOME variable inside flatpak will differ, so we additionally have to override the config location. 

```bash
$ sudo flatpak override --filesystem=host com.github.miguelmota.Cointop
$ sudo flatpak override --env=COINTOP_CONFIG=$HOME/.config/cointop/config.toml 
$ flatpak run com.github.miguelmota.Cointop
```

With the above overrides, the config will be in the default location `~/.config/cointop/config.toml` of host user.
