### ISSUE TITLE
Add Bitcoin Satoshi support to Currency Conversion options

### ISSUE THREAD

**Issue by githorray** [miguelmota/cointop#125]
When viewing many coins with BTC currency conversion, the Bitcoin price shown is 0.00.

It would be great to see the smaller amounts in Bitcoin Satoshis instead.

https://en.bitcoin.it/wiki/Satoshi_(unit)
https://satsymbol.com/

Thanks again for an awesome tool. :)

**Comment by simon-anz** [comment]
Was fixed by #132
![Screen Shot 2021-08-23 at 7 50 28 am](https://user-images.githubusercontent.com/69175652/130371094-f2ccbd04-c8b4-4c6a-9e4d-1ad9f5fcbfc2.png)

**Comment by simon-anz** [comment]
Except for very low-price coins (eg: SHIB stills shows as 0.00 since it would be 0 to 8dp)

**Comment by miguelmota** [comment]
Maybe the number of decimal places can be extend up to 12 instead of 8? like how CoinGecko does it

**Comment by lyricnz** [comment]
Created a PR for this
https://github.com/miguelmota/cointop/pull/175/files?diff=split&w=1
Interestingly BTC shows up as not-exactly 100 million, but this matches the data that coingecko exposes
![Screen Shot 2021-09-25 at 10 31 14 am](https://user-images.githubusercontent.com/122371/134751760-082c691c-28e0-4d50-9c5e-33a9ebad928f.png)

```
    {
        "id": "bitcoin",
        "symbol": "btc",
        "name": "Bitcoin",
        "image": "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
        "current_price": 100071984,
        "market_cap": 1882555741642987,
```

**Comment by lyricnz** [comment]
Hopefully this matches the OP request (DOGE is 494.50 SATS, rather than 0.00000495 BT
![Screen Shot 2021-09-25 at 10 33 17 am](https://user-images.githubusercontent.com/122371/134751835-8e856d18-70e4-49a6-9c88-47f9e7dacd3d.png)
C)

**Comment by lyricnz** [comment]
Close. https://github.com/miguelmota/cointop/pull/175/files?diff=split&w=1
