### ISSUE TITLE
Optimized Docker image

### ISSUE THREAD

**Issue by braderhart** [miguelmota/cointop#127]
I created an optimized Docker image here:

https://hub.docker.com/r/equalos/cointop

This reduces the size down to 3.43 MB compressed. You can find the Dockerfile here:

https://gitlab.com/equalos/skaffold/blob/master/cointop/docker/cointop/Dockerfile

Please let me know if you see any issues.

**Comment by miguelmota** [comment]
Hi @braderhart, will definitely check it out!

**Comment by simon-anz** [comment]
Dockerfile link is actually
https://gitlab.com/equalos/skaffold/-/blob/main/cointop/docker/cointop/Dockerfile

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/5f76e89a0be481796fe1c33bc75beb4966c6fbe1

**Comment by miguelmota** [comment]
Thanks again @braderhart. Dockerfile size is greatly improved
