### ISSUE TITLE
Add 30d and 1 year change in the listing row for cointop

### ISSUE THREAD

**Issue by rpulikool** [miguelmota/cointop#131]
Can you please add the feature to include the  30d and 1 year change on the cointop so it will list more data. As of now it doesn't list that data

**Comment by simon-anz** [comment]
Hotkey changed to "y" and merged.  How's that look @rpulikool ?  Either wait for a release, or pull <master> and build it yourself.

**Comment by lyricnz** [comment]
I think we can close this - 30d and 1y date ranges are available, and the hotkey is changed to 'y'.
