### ISSUE TITLE
Decimal places not shown

### ISSUE THREAD

**Issue by delgardoxx** [miguelmota/cointop#132]
For some tokens that have a very low value, no decimal places are displayed. Example: Shiba Inu with 0.000007350 EUR
<img width="262" alt="Bildschirmfoto 2021-06-01 um 18 07 24" src="https://user-images.githubusercontent.com/39244978/120356066-3caa2080-c304-11eb-82ed-4e242602e4b7.png">

**Comment by keybreak** [comment]
Indeed, i would also add that it would be perfect if decimals were also separated by space each 3, like:
0.000 000 000 77

very useful for memecoins

**Comment by simon-anz** [comment]
![Screen Shot 2021-08-23 at 7 48 56 am](https://user-images.githubusercontent.com/69175652/130371044-61b0699f-2ac9-490d-8b39-ce644833e662.png)
Seems to be resolved

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/758e8367f7d37c0e049e359f0ddb74d7ac2c3976
