### ISSUE TITLE
in portfolio add non wanted coin

### ISSUE THREAD

**Issue by ronki2304** [miguelmota/cointop#136]
Hello team,

if you add auto token (from autofarm) in your portfolio, other token with i suppose the same coin identifier are added :
![image](https://user-images.githubusercontent.com/25466164/129732236-50aacb96-34cb-48eb-ac58-dedf78a38884.png)

is it possible to remove them

thank you in advance

**Comment by simon-anz** [comment]
Duplicate of #130

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/pull/138
