### ISSUE TITLE
Ability to set default date-range for charts

### ISSUE THREAD

**Issue by simon-anz** [miguelmota/cointop#139]
Rather than starting on yearly, it would be good to save the setting and/or make it configurable in config file.

**Comment by simon-anz** [comment]
Created a PR for this https://github.com/miguelmota/cointop/pull/140/files?diff=split&w=1

This loads the default from config file, and does not (yet?) save the current-range back.

**Comment by miguelmota** [comment]
Thanks @simon-anz! I think it would maybe make sense to store the last chosen date range in the file cache, which can be done in a later PR
