### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by skiwithpete** [miguelmota/cointop#141]
Hi,

1.6.6 is not yet available in the docker container found here:

https://hub.docker.com/r/cointop/cointop/tags?page=1&ordering=last_updated

Is there another location for the docker that is preferable?

**Comment by miguelmota** [comment]
@skiwithpete Thanks for the heads up. The docker image is now tagged and pushed

![DeepinScreenshot_select-area_20210822154050](https://user-images.githubusercontent.com/168240/130372295-f673c217-9efe-442c-9e6c-b4efcd4c1ae7.png)
