### ISSUE TITLE
Duplicate coins (same symbol, different name) overwrite each other in cache

### ISSUE THREAD

**Issue by simon-anz** [miguelmota/cointop#145]
While investigating #144 discovered that coins use only their Symbol when generating a cache-key for saving. However, there are potentially multiple coins with the same symbol, which means these will overwrite/use the same file.

In fact coingecko.GetCoinGraphData(convert, symbol, name, ...) doesn't even use the Symbol, it only uses Name.

I haven't actually experienced this issue (perhaps it is not possible with changes from #138), but it's at least a theoretical risk.  Realistically, the prices should be pretty close, so maybe it's "good enough" as is.

**Comment by lyricnz** [comment]
See #176
