### ISSUE TITLE
Expression evaluator crashes when given parameter-like expression

### ISSUE THREAD

**Issue by simon-anz** [miguelmota/cointop#152]
Since #149 entering an expression like "xxx" causes cointop to crash. This appears to be a reoccurrence of https://github.com/Knetic/govaluate/issues/65 with the same fix/workaround - passing an empty set of parameters, rather than nil.

**Comment by simon-anz** [comment]
This could be caused by the way in which the module is packaged in /vendor?
https://github.com/miguelmota/cointop/tree/master/vendor/github.com/Knetic/govaluate
But my stack trace had
/Users/robers11/go/pkg/mod/github.com
```
$ ./bin/cointop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1342286]

goroutine 1 [running]:
github.com/Knetic/govaluate.makeParameterStage.func1({0x19b5108, 0x0}, {0x0, 0xc000830d38}, {0x0, 0x0})
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/evaluationStage.go:217 +0x26
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage({{0x14fdc0e, 0x22}, 0x1, {0xc000288090, 0x1, 0x1}, 0xc00008ca00, {0xc0008a7165, 0x3}}, 0xc00008ca00, ...)
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:228 +0x523
github.com/Knetic/govaluate.EvaluableExpression.Eval({{0x14fdc0e, 0x22}, 0x1, {0xc000288090, 0x1, 0x1}, 0xc00008ca00, {0xc0008a7165, 0x3}}, {0x0, ...})
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:159 +0x115
github.com/Knetic/govaluate.EvaluableExpression.Evaluate({{0x14fdc0e, 0x22}, 0x1, {0xc000288090, 0x1, 0x1}, 0xc00008ca00, {0xc0008a7165, 0x3}}, 0x0)
	/Users/robers11/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:134 +0xf2
github.com/miguelmota/cointop/pkg/eval.EvaluateExpressionToFloat64({0xc0008a7165, 0xc000cc389c})
	/Users/robers11/src/github/cointop/pkg/eval/eval.go:20 +0x15b
```

Sorry, I'm not familiar with golang packaging??

**Comment by simon-anz** [comment]
Looks like the bug was fixed on 25 July 2017
https://github.com/Knetic/govaluate/commit/beae3c74e5d7b39c0674bc525b5fe6fd0167e47d
But the last official release was (earlier) 1 May 2017
https://github.com/Knetic/govaluate/releases
So we probably need HEAD not the latest release

**Comment by simon-anz** [comment]
Don't merge the PR - either upgrade to govaluate HEAD, or switch to a different library

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/pull/154
