### ISSUE TITLE
Issue with currencies using same symbol

### ISSUE THREAD

**Issue by SevenIndirecto** [miguelmota/cointop#16]
Problem seems to occur when at least two currencies share the same symbol. Cointop will seemingly randomly load either one on startup. 

Current example would be the symbol HOT which is used by Holochain and Hydro Protocol. 

* Searching only finds one or the other (depending on which loaded at startup?).
* Even when marking one as favourite and saving, on subsequent loads 'randomly' one of the two mentioned currencies will appear as favoured.

**Comment by miguelmota** [comment]
@SevenIndirecto yes you're right, this is indeed a bug where it's storing the symbol rather than the full name. Will fix it in the next release
