### ISSUE TITLE
Question about similar application

### ISSUE THREAD

**Issue by MostHated** [miguelmota/cointop#160]
Hey there,
    Cointop is great, I use it to output my data to file then grab it with Conky to display in my system stats panel. I was wondering if there happens to be something similar that anyone knows about for stocks? I know there are a few terminal based stock tickers and such, but I can't seem to locate any that allow you to have listed holdings and then output straight to a file without having to keep that app up and running at all times. If anyone knows of any, I would definitely appreciate it. 

At the same time, I know this post is not on topic, so if you want/need to close/remove it, I certainly understand. 

Thanks,
-MH

**Comment by simon-anz** [comment]
Seems like there should be more straight-forward ways of grabbing data from a source, and writing it to a file (would only be a few lines of code).   Each exchange typically has an API, which requires (relatively simple) code to fetch and save.  If you know of a public API for stocks, it shouldn't be too hard to find someone to write that for you.

Cointop mostly uses https://www.coingecko.com/ for data, which only supports crypto.

**Comment by MostHated** [comment]
Heya, I appreciate the reply. Yeah, for sure, I would imagine there are a good number of api's to hit, I was just wondering if something happened to exist already, it definitely seems like there would be, but perhaps not. 

Honestly, it's not a big enough concern to go create a whole new thing to do it, but, if there had happened to be something that already existed that would allow me to borrow from what I had already done with cointop, I would be all about it.

**Comment by MostHated** [comment]
I appreciate the ideas, this ended up working out perfectly. https://github.com/pstadler/ticker.sh

**Comment by simon-anz** [comment]
Cool.  Looks pretty minimal!  Close this issue if you're satisfied.
