### ISSUE TITLE
Suggestion - use a logging framework

### ISSUE THREAD

**Issue by simon-anz** [miguelmota/cointop#161]
In order to provide more control over log output (and integrate better with libraries), cointop could use a logging framework rather than an `if debug log.printf` in https://github.com/miguelmota/cointop/blob/master/cointop/debug.go

It feels like having to have the `Cointop ct` context is awkward?

From reading https://www.honeybadger.io/blog/golang-logging/ logrus appears to be the pretty-much the consensus https://github.com/Sirupsen/logrus

**Comment by simon-anz** [comment]
Raised a PR for this. Uses existing code for file initialization, and sets log-level to Debug only when $DEBUG is set (per current)

```
	if os.Getenv("DEBUG") != "" {
		log.SetLevel(log.DebugLevel)
	}
```

The output file /tmp/cointop.log is opened unconditionally, since (future) code may output at higher level.

**Comment by simon-anz** [comment]
Future enhancement: configuration of logfile location, log level, output format, etc

**Comment by miguelmota** [comment]
Setting `log.SetReportCaller(true)` is a bit noisy but there are ways to modify it to just show the filename and line number ([gist](https://gist.github.com/miguelmota/0508139b2df9142b4574dba2edb6fb9b))

**Comment by simon-anz** [comment]
PR is merged, further enhancements can be raised as feature-requests.
