### ISSUE TITLE
Unused variable - strconv.FormatFloat(percentChange24H,..)

### ISSUE THREAD

**Issue by simon-anz** [miguelmota/cointop#166]
The first `value` is never used.  Should the first line be used, and optionally append `%`, or the if/else be used as-is and the first line removed?

```golang
	value := strconv.FormatFloat(percentChange24H, 'f', -1, 64)

	if humanReadable {
		value = fmt.Sprintf("%.2f%%", percentChange24H)
	} else {
		value = fmt.Sprintf("%.2f", percentChange24H)
	}
```

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/b6c0579b38f1942677415092c906c7c6b5051efe
