### ISSUE TITLE
holdings: bug with REN coin

### ISSUE THREAD

**Issue by mrlogick** [miguelmota/cointop#169]
If you insert some amount to Ren (REN), then you get that amount to both Ren and Rinnegan coins. I think the problem is because Rinnegan has the same "REN" symbol.

**Comment by simon-anz** [comment]
Which release are you on?  There was a fix for this in #130 applied last month.  See https://github.com/miguelmota/cointop/releases

**Comment by simon-anz** [comment]
![Screen Shot 2021-09-21 at 9 24 44 am](https://user-images.githubusercontent.com/69175652/134089399-d3d74865-e843-4ca9-afcc-bc821d272cc3.png)
Seems to work ok for me: v1.6.8

**Comment by mrlogick** [comment]
Yes sorry, after update, I no longer have the problem.
