### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [miguelmota/cointop#17]
Sorry for not having the template
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs if you are needing it. Hoping for your positive response Thank You!

**Comment by miguelmota** [comment]
Hi @jbeguna04 , thanks for the suggestion but we're current sticking with the current logo for cointop. Thanks!

**Comment by jbeguna04** [comment]
Thank you for your response
