### ISSUE TITLE
Buff Doge Coin - Ghost

### ISSUE THREAD

**Issue by WildBillDoE** [miguelmota/cointop#171]
Buff Doge Coin just appeared in my Cointop Portfolio out of nowhere. It appears to have duplicated my Dogecoin Holdings. 
I can not get rid of it, and it is not listed in the config.toml file.
Sample: 
cointop holdings
Buff Doge Coin  DOGECOIN

**Comment by WildBillDoE** [comment]
NM: I updated to v1.6.8. Problem seems solved.

**Comment by WildBillDoE** [comment]
Reopened because it came back a few times now.

**Comment by simon-anz** [comment]
Problem is related to duplicate symbols. Try deleting it from your portfolio, then restarting cointop, then it will probably show again, then delete that, and restart.

(problem is that there are TWO entries in your config file, one of which is being hidden as duplicate, but when you delete the dupe, the first one comes back).

**Comment by simon-anz** [comment]
Appears to be a scammy coin designed to trick users https://www.coingecko.com/en/coins/buff-doge-coin
