### ISSUE TITLE
CHANGELOG.md is out of date

### ISSUE THREAD

**Issue by lyricnz** [miguelmota/cointop#173]
[CHANGELOG.md](https://github.com/miguelmota/cointop/blob/master/CHANGELOG.md) only goes up to 1.6.2

Is there a tool to help build this from https://github.com/miguelmota/cointop/releases ?

**Comment by miguelmota** [comment]
I've been manually updating CHANGELOG.md to keep things simpler  to make it more user-friendly since autogenerated changelogs tend to be noisy (maybe there can be another autogenerated changelog?).

I just updated CHANGELOG.md so it's up-to-date

**Comment by lyricnz** [comment]
No need for an additional changelog, I reckon - https://github.com/miguelmota/cointop/releases is good
