### ISSUE TITLE
additional currency

### ISSUE THREAD

**Issue by raphson93** [miguelmota/cointop#18]
hi can you please add MYR as part of the currency ?

Thank you

**Comment by miguelmota** [comment]
@raphson93 will be adding additional currencies that in the next release

**Comment by NotStatilko** [comment]
@miguelmota 

Can you please add Ukrainian Hryvnia ([**UAH**](https://en.wikipedia.org/wiki/Ukrainian_hryvnia))?

**Comment by miguelmota** [comment]
@NotStatilko added ([commit](https://github.com/miguelmota/cointop/commit/d8cbc89e5c096bcd23b1d7f56a9300c593e91225)). Available on main branch.

**Comment by NotStatilko** [comment]
> @NotStatilko added ([commit](https://github.com/miguelmota/cointop/commit/d8cbc89e5c096bcd23b1d7f56a9300c593e91225)). Available on main branch.

Thank you very much!
