### ISSUE TITLE
Remove dependencies from pkg folder and manage with go modules

### ISSUE THREAD

**Issue by cjbassi** [miguelmota/cointop#24]
Hi, really cool project! Is there a reason that several dependencies are stored in the `pkg` folder, rather than managed with go modules and stored in `vendor`? I was curious what rendering library you were using (termui vs gocui) and I didn't see either in `go.mod`, but noticed both libraries are stored in the `pkg` folder. Looks like there's also `go-cache`, `termbox`, `now`, and maybe some others too.

**Comment by miguelmota** [comment]
@cjbassi i think originally it was because of two reason: i was pretty new to Go and didn't understand dependencies and also I might of needed to modify some vendor pkgs. You're right though in that they should be in the vendor directory. The whole codebase needs a clean up
