### ISSUE TITLE
Failed to ping

### ISSUE THREAD

**Issue by riscphree** [miguelmota/cointop#26]
Installed via homebrew on osx. First run ran fine. However, after exiting and attempting to run again I am presented with:

```
$ cointop
2019/02/27 00:33:15 failed to ping

```
I've tried this on a second machine with the same results, also from homebrew
OSX 10.12.6
```
$ brew --version
Homebrew 2.0.2
Homebrew/homebrew-core (git revision de949; last commit 2019-02-26)
Homebrew/homebrew-cask (git revision 18160; last commit 2019-02-27)
```

**Comment by miguelmota** [comment]
@riscphree thanks for reporting. Looks like it's due to a CoinMarketCap api response failure. I hope they didn't put more restrictions on api calls

will look into it..

**Comment by riscphree** [comment]
If that's the case, they do have a free option in which users could put their own API key in.

**Comment by cocoonkid** [comment]
Same issue here. Looking forward to a way to add private API key.

**Comment by tf-anguskong** [comment]
I'm getting this same issue, I've tried this on multiple machines and it replicates exactly on each one. If I install it for the first time (using snap) it runs the first time without issue. Closing and reopening it will cause the "failed to ping" error.

Yes, if there was a way to add a private API key (maybe in the config file?) that would be fantastic! Regardless, I am a fan; and I wish I had a better idea how to develop or I would help out.

**Comment by miguelmota** [comment]
Sorry for the delay guys, finally pushed an update; Cointop version 1.1.4 is using the CoinMarketCap Pro API. You can specify the API key in the config file:

```toml
[coinmarketcap]
  pro_api_key = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
```

Alternatively, you can export the API key in .bashrc

```bash
export CMC_PRO_API_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
