### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by ttygde** [miguelmota/cointop#27]
Is there a way to change columns, disable top/bottom bar or change colors? Bt the way something is wrong with fullscreen it seems, screenshot attached.
![wqis](https://user-images.githubusercontent.com/6169944/53486183-e2c5ab00-3aa9-11e9-958c-97fb9daab3b7.png)

**Comment by miguelmota** [comment]
@asmbits currently there's no way to change columns or disable bars or change colors but those are all great features that should be added (when there's spare time to work on them or if someone can help out)

**Comment by miguelmota** [comment]
Cointop now has the following flags:

- `--only-table` flag to show only the table.
- `--hide-marketbar` flag to hide the top bar.
- `--hide-chart` flag to hide the chart.
- `--hide-statusbar` flag to hide the bottom statusbar.

Visit https://github.com/cointop-sh/colors for instructions on adding custom themes
