### ISSUE TITLE
How to watch price graph of Bitcoin?

### ISSUE THREAD

**Issue by jasonzhouu** [miguelmota/cointop#28]
What's the graph on the top used for?
Hot to switch the graph to show the price curve of Bitcoin?
![image](https://user-images.githubusercontent.com/19926174/56017214-28c09080-5d31-11e9-883b-0ff24577d324.png)

**Comment by miguelmota** [comment]
Bug is fixed in Cointop version 1.1.4. Related to issue https://github.com/miguelmota/cointop/issues/26
