### ISSUE TITLE
Add custom refresh setting

### ISSUE THREAD

**Issue by jfarid27** [miguelmota/cointop#30]
**Is your feature request related to a problem? Please describe.**
Coinmarket cap is now **requiring** an API key for the use of their API. A fresh install currently logs `Pro API Key is required`.  A basic account only has about 333/day requests, so it looks like there might need to be a way to either turn off polling or reduce the refresh rate.

**Describe the solution you'd like**
A customizable setting in the config file that will accept a refresh rate argument. It should accept a way to completely turn off refresh rates to force the user to manually refresh, and it should accept a numeric value for a refresh rate.

**Describe alternatives you've considered**

**Additional context**
None really.

**Comment by miguelmota** [comment]
@jfarid27 great idea. Will implement a refresh rate config option

**Comment by miguelmota** [comment]
You can now run cointop with the flag `--refresh-rate 60` where the value is the number of seconds that it will fetch for data. You can also set the refresh rate in the config file:

```toml
refresh_rate = 60
```
