### ISSUE TITLE
Flatpak crashes

### ISSUE THREAD

**Issue by barkingbandicoot** [miguelmota/cointop#31]

**Comment by barkingbandicoot** [comment]
> A clear and concise description of what the bug is.

 After start the flatpak crashes.
It was working - perhaps broken after a cointop update.

Operating System 
Kubuntu 19.04

**Comment by miguelmota** [comment]
@barkingbandicoot thanks for reporting; will look into it

**Comment by miguelmota** [comment]
Closing in favor of https://github.com/miguelmota/cointop/issues/32
