### ISSUE TITLE
Missing font/chars in chart

### ISSUE THREAD

**Issue by saddy123** [miguelmota/cointop#310]
Hey, I am running an updated arch linux.

First tried the aur package and then the go install method after I saw the broken chart.
![cointopbrokenchart](https://user-images.githubusercontent.com/3920565/175108326-1d1f0dfa-39ef-4651-9074-633e4a894044.jpg)

I guess I am missing some font or another dependency. 

Ty for your thoughts

**Comment by lyricnz** [comment]
The characters actually look OK (look at the filled dots, not just the hollow ones), but your font has chosen to draw the 8-dot glyphs (aka font braille dots) with hollow circles all.  Nothing we can do on our side - you need to select a font with a better rendering of braille dots.

**Comment by saddy123** [comment]
Many thanks! The font Source Code Pro Medium now produces nice dots for me
