### ISSUE TITLE
App crashes at startup. Takes console along with it.

### ISSUE THREAD

**Issue by oliverkane** [miguelmota/cointop#33]
Hi there.  I was attempting to use your tool on Ubuntu 19.04 with a pretty fresh install of the OS with few modifications.  The app seems to crash and locks up the terminal along with it.  I've included a screenshot of the error and will try to get the crashlog in text form momentarily. I believe the most recent update made this crash happen rather in a few seconds to immediately upon start.  

If there's other details you'd like or would find helpful, please let me know.

It does change the behavior for me, but now it insta-crashes.  I've installed from source via the `go get` command and not from a package manager.  I'll be around today at the keys if you want more details.  

go version go1.12.3 linux/amd64

![image](https://user-images.githubusercontent.com/1761622/58751798-4d9bcf00-8469-11e9-9e5f-1c00f348e353.png)

![image](https://user-images.githubusercontent.com/1761622/58751783-12010500-8469-11e9-97ae-47822353f265.png)

**Comment by miguelmota** [comment]
@oliverkane thanks for info. I was able to reproduce the problem on an ubuntu machine and pushed updated code. Can you try the latest `go get -u github.com/miguelmota/cointop` and see if it crashes for you still

**Comment by oliverkane** [comment]
Works like a dream.  Thanks!

Didn't see a public address in your readme.md.  Do you accept crypto tips?

**Comment by miguelmota** [comment]
@oliverkane cool! 

added a tip jar to the [README](https://github.com/miguelmota/cointop#tip-jar). Thanks!
