### ISSUE TITLE
Fail to start in Windows 10. 

### ISSUE THREAD

**Issue by Rohit036** [miguelmota/cointop#34]
I installed go, latest version and used the command for windows go get -u github.com/miguelmota/cointop. It did not show any error and came to next line. 
I used cointop to start but error shows up. 

```
C:\Users\RohitSingh>go get -u github.com/miguelmota/cointop

C:\Users\RohitSingh>cointop
time="2019-06-11T21:11:07+05:30" level=fatal msg="mkdir : The system cannot find the path specified."
```

**Comment by miguelmota** [comment]
@Rohit036 Thanks for reporting the bug. Will debug when I get access to a Windows machine

**Comment by rcdosado** [comment]
this bug also appears when cointop.exe is run in Windows 7

**Comment by miguelmota** [comment]
@Rohit036 @rcdosado 

There's new updates regarding the mkdir command for creating the config file.
Can you try `go get -u github.com/miguelmota/cointop` again? Thanks

**Comment by miguelmota** [comment]
Alright finally tested it on a Windows machine. Should be good now. Thank you for your patience!

![33c24651-d813-430f-8117-74bb05aa3f1e](https://user-images.githubusercontent.com/168240/60704695-02d30400-9eba-11e9-8cd3-a19bc5476048.png)

**Comment by stefan52a** [comment]
Had to do 

mkdir c:\tmp
