### ISSUE TITLE
Price displayed in scientific format on y-axis (bitcoin price is high)

### ISSUE THREAD

**Issue by inbredtom** [miguelmota/cointop#35]
<img width="756" alt="Screenshot 2019-06-18 at 23 19 33" src="https://user-images.githubusercontent.com/6849705/59720599-90a6c200-921f-11e9-96ba-aa05d0851576.png">

note the price in the table is displayed "nicely".

raspberry pi
go version 1.10.1 linux/arm

**Comment by miguelmota** [comment]
@inbredtom thanks for reporting the bug. Should look better now

<img width="1221" alt="Screen Shot 2019-06-26 at 12 11 16 AM" src="https://user-images.githubusercontent.com/168240/60159592-69646d80-97a8-11e9-97a4-918ea6c078f3.png">
