### ISSUE TITLE
panics on concurrent map access

### ISSUE THREAD

**Issue by Pomyk** [miguelmota/cointop#36]
It still panics on concurrent map access. Cointop.allcoinsslugmap and Colorscheme.cache should be guarded by mutexes.

**Comment by miguelmota** [comment]
Thanks for the suggestions. Will debug it

**Comment by Pomyk** [comment]
Or maybe use a sync.Map?

**Comment by miguelmota** [comment]
Alright it's using a sync.Map [now](https://github.com/miguelmota/cointop/commit/db3cb706969cc7ef4e791d1e718c7590537dbbe2) for the maintaining map of coins
