### ISSUE TITLE
No decimals after the prices of some assets

### ISSUE THREAD

**Issue by shanefontaine** [miguelmota/cointop#37]
Certain assets do not display any digits on the right side of the decimal. Some examples are BTC and USDT in the image below.

<img width="1236" alt="Screen Shot 2019-06-20 at 11 06 06 AM" src="https://user-images.githubusercontent.com/9441295/59871064-8b469600-934b-11e9-952f-48ce187d8437.png">

**Comment by miguelmota** [comment]
Should be better now:

<img width="605" alt="Screen Shot 2019-06-25 at 11 16 14 PM" src="https://user-images.githubusercontent.com/168240/60155519-408baa80-979f-11e9-9453-8681891cdb4e.png">

However sometimes the CoinGecko API will return values without a decimal place:

Bitcoin example:

<img width="1184" alt="Screen Shot 2019-06-25 at 10 36 40 PM" src="https://user-images.githubusercontent.com/168240/60155424-ee4a8980-979e-11e9-91ce-f99cbc1c3fd3.png">

Tether example:

<img width="1188" alt="Screen Shot 2019-06-25 at 11 12 09 PM" src="https://user-images.githubusercontent.com/168240/60155431-f5719780-979e-11e9-9a77-15cea47c1b41.png">
