### ISSUE TITLE
Cointop fails to install in Termux

### ISSUE THREAD

**Issue by Mhowser** [miguelmota/cointop#39]
I get this when I try to install in Termux

```
$ go get -u github.com/miguelmota/cointop
# github.com/miguelmota/cointop/vendor/github.com/fatih/color
go/src/github.com/miguelmota/cointop/vendor/github.com/fatih/color/color.go:21:43: undefined: isatty.IsCygwinTerminal
```

**Comment by Mhowser** [comment]
Any progress on this bug?

**Comment by miguelmota** [comment]
Haven't been able to replicate problem, but I also don't have an android device with Termux available. Help wanted

**Comment by miguelmota** [comment]
Alright I found [this](https://github.com/mattn/go-isatty/issues/31) and [this](https://github.com/mattn/go-isatty/pull/33) on the go-isatty issues which means there was a missing method for android. I pushed a [fix]() so give it another go and let us know 

@Mhowser

**Comment by Mhowser** [comment]
It installed successfully! Only problem is that I don't know how to add it to my $PATH

**Comment by Mhowser** [comment]
I found out the command, which is `PATH=$PATH:~/go/bin` thanks for the fix!

**Comment by miguelmota** [comment]
Nice!
