### ISSUE TITLE
Enter key doesn't work on Ubuntu

### ISSUE THREAD

**Issue by popey** [miguelmota/cointop#4]
I built a snap of cointop which you can install on Ubuntu (and other distros) with `snap install cointop`. However pressing Enter on a line doesn't launch a browser (as I expect it should). It appears that cointop calls `/bin/openvt` when it might be better to just call `xdg-open` (without the path) which is a more robust way of launching URLs on Linux AIUI.

**Comment by popey** [comment]
Sadly it doesn't fix the issue on Linux. I've pushed the latest build to the edge channel. This can be tested with `snap install cointop --edge` or if you already have it installed `snap refresh cointop --edge`.

**Comment by str** [comment]
Shouldn't `enter` change the chart by the selected coin?

**Comment by miguelmota** [comment]
Just pushed a bugfix that fixes the ability to open links in Linux/Ubuntu
