### ISSUE TITLE
Why not `os.UserHomeDir()`

### ISSUE THREAD

**Issue by LakeVilladom** [miguelmota/cointop#40]
https://github.com/miguelmota/cointop/blob/f1e3f81ec086815dfd26feab4fd44c7a3ff9bc80/cointop/util.go#L32

**Comment by miguelmota** [comment]
@LakeVilladom `os.UserHomeDir()` doesn't include `XDG_CONFIG_HOME` which was a requested feature of a few users

https://github.com/golang/go/blob/85525c56ab5fdb214fee70b4b4cce8700344258b/src/os/file.go#L389

**Comment by miguelmota** [comment]
actually, I could refactor it to use os.UserHomeDir() and have another method for getting the user home config path

**Comment by LakeVilladom** [comment]
I found the same problem in this project: [sqshq/sampler] (https://github.com/sqshq/sampler/blob/5eb260b432074b01d32cd4d7e07035bb06157d88/metadata/storage.go#L23), which uses the third-party library `github.com/mitchellh/go-homedir'.

Personally, I prefer to use the Go standard library rather than a third-party library.

Suggestions to Go Officials?

Forgive me for my poor English

**Comment by miguelmota** [comment]
It's updated now to use `os.UserHomeDir()`
