### ISSUE TITLE
Double Entry for Portfolio and Favorites

### ISSUE THREAD

**Issue by cidadededeus36** [miguelmota/cointop#41]
Hi tried marking my favorites and tested out the portfolio feature. It is for some reason showing me two entries for Bitcoin in portfolio and favorites. Resulting in double the value of my holdings

**Comment by miguelmota** [comment]
@cidadededeus36 thanks for reporting the bug. Which method did you use to install cointop?

**Comment by cidadededeus36** [comment]
I installed cointop from source. I noticed also that occasionally the entry with the most value in my portfolio would end up being ranked first on the coin rank list when exiting portfolio view

**Comment by miguelmota** [comment]
Fixes regarding the sorting were pushed this morning (v1.3.5). Try updating again and see if there's a difference

**Comment by cidadededeus36** [comment]
Upgrade to v1.3.5. I no longer experience double entrys. Im still experiencing the issue mentioned earlier concerning coin rank list. I noticed it fixes itself sometimes if you leave it on the screen for a min

**Comment by miguelmota** [comment]
Your right, i'm seeing that now. Will keep debugging

**Comment by miguelmota** [comment]
Discovered the issue and should be fixed in master (version 1.3.6)
