### ISSUE TITLE
v1.3.6 locks

### ISSUE THREAD

**Issue by ndowens** [miguelmota/cointop#43]
I maintain the cointop port on FreeBSD and I upgraded it to the latest version 1.3.6 released so far, on my system. After opening cointop, it seems to freeze after the data is shown on screen. Can not hit Enter, go up or down, or even quit.

**Comment by miguelmota** [comment]
Thanks for reporting the issue and maintaining the FreeBSD port! That's a strange bug, maybe something is causing an endless loop. I'll look into it when time is available

**Comment by miguelmota** [comment]
The issue is with the TUI library cointop is using ([gocui](https://github.com/jroimartin/gocui)). Planning on migrating to the TUI library [tcell](https://github.com/gdamore/tcell) at some point since a simpler library and has no issues with keybindings.

**Comment by miguelmota** [comment]
The keybinding issue on freebsd was [fixed](https://github.com/nsf/termbox-go/pull/219/files) on the dependency package. Will create a new release soon.
