### ISSUE TITLE
Feature request: Price alerts

### ISSUE THREAD

**Issue by eingedanke** [miguelmota/cointop#47]
Hi,

Would it be possible to add support for the BEST coin?
https://www.coingecko.com/en/coins/bitpanda-ecosystem-token

Also, would it be easy to implement price alerts?
E.g. indicating price alerts on the graph by a horizontal line would already be nice.
Then, alerting the user somehow if an alert was triggered would be a plus.

**Comment by miguelmota** [comment]
Increased the number of page results that coingecko returns so it should show the BEST coin now in the v1.4.6 release

The price alerts feature is something I'd love to implement but don't have enough time. Always open to accepting pull requests.

**Comment by miguelmota** [comment]
Basic alert functionality has been added and available on the main branch.

![Peek 2021-02-01 01-25](https://user-images.githubusercontent.com/168240/106440029-36c33200-642d-11eb-81fa-1b3395a56efe.gif)
![Screenshot from 2021-02-01 01-31-22](https://user-images.githubusercontent.com/168240/106440042-3a56b900-642d-11eb-93ac-ccc18f299ac0.png)

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/cba53fe5d40d74c11daa68b172b282cbce9117c5

**Comment by gustavomassa** [comment]
@miguelmota I can't find the documentation/shortcut about how to configure/view price alerts

**Comment by lyricnz** [comment]
The help menu is always available at '?' key.   

 + show_price_alert_add_menu
A toggle_price_alerts

But yes, this feature is not well documented.
