### ISSUE TITLE
Graph is always showing dollar price

### ISSUE THREAD

**Issue by eingedanke** [miguelmota/cointop#48]
When switching the currency to e.g. Euro, the price shows correctly in the table, but the graph still shows the Dollar price.
I've tried to refresh the graph, changed lots of settings, deleted my user settings, etc. but it keeps behaving that way.

![2020-02-03-114338_942x265_scrot](https://user-images.githubusercontent.com/31983813/73646727-54bf5080-467a-11ea-945c-a32d1917e5a8.png)

**Comment by hmble** [comment]
When I checked [`GetCoinGraphData`](https://github.com/miguelmota/cointop/blob/c3aa7bf5b3f21704e7b2bbac3822edcc5d2b7873/cointop/common/api/impl/coingecko/coingecko.go#L134). In here `"usd"` is explicitly called instead of selected currency.

**Comment by hmble** [comment]
hey @eingedanke could you check if this pull request solves your issue ? It seems to work for me though
