### ISSUE TITLE
Ethereum won't update

### ISSUE THREAD

**Issue by FlipFloop** [miguelmota/cointop#52]

**Comment by miguelmota** [comment]
Trying to get more context, are you saying only the ethereum price doesn't update?

**Comment by FlipFloop** [comment]
Yes!

**Comment by hmble** [comment]
Sometimes the values aren't updated maybe becuase no updates returned from coingecko.com api. Also after looking from source code maybe [api request](https://www.coingecko.com/market_cap/total_charts_data?duration=7&locale=en&vs_currency=usd) only returns data for days and not hours.

Confirming chart update on different range it seems the chart doesn't update for values less than 24H ( 1 day ).

@FlipFloop could you confirm stated scenario above ?

**Comment by FlipFloop** [comment]
Yes!

**Comment by hmble** [comment]
I think we could remove hour range from option. @miguelmota

**Comment by miguelmota** [comment]
< 24H options have been removed in v1.4.5
