### ISSUE TITLE
"not enough data for chart" error on startup

### ISSUE THREAD

**Issue by githorray** [miguelmota/cointop#54]
Started getting weird quotes yesterday.

Today getting "not enough data for chart" on cointop startup.

Using latest version from github.

![image](https://user-images.githubusercontent.com/39980780/87124779-f434df00-c2bb-11ea-8f3f-68b11e54c76c.png)

**Comment by githorray** [comment]
Starting working again. Closing.

**Comment by miguelmota** [comment]
Thanks for the bug report. I believe it happened because the request to fetch data failed. Not exactly sure why but will look into it.

**Comment by githorray** [comment]
I have to keep using `cointop --reset` to get a proper display. :(
