### ISSUE TITLE
Ability to output portfolio holding amount

### ISSUE THREAD

**Issue by Emobe** [miguelmota/cointop#55]
Is there a way I can get cointop to output my current holdings? Specifically the entire holdings in fiat. If not can this be implemented?

**Comment by miguelmota** [comment]
@Emobe the total portfolio value in fiat is visible at the top of the chart as seen in this example: 

![Screenshot from 2020-07-31 01-21-31](https://user-images.githubusercontent.com/168240/89015618-2e4a3d00-d2cc-11ea-814c-cd0eaeb4e0c4.png)

Or did you mean output the holdings as in by running a command?

**Comment by wokawoka** [comment]
being able to check the total portfolio value from the command line would be indeed fantastic. Is there a way to achieve that?
Thanks !

**Comment by miguelmota** [comment]
@wokawoka there's isn't a way yet. I'll include this feature in a future release!

**Comment by wokawoka** [comment]
> @wokawoka there's isn't a way yet. I'll include this feature in a future release!

great, we are really looking forward for it, it would be just great!

As a side note, is there by chance a way to retrieve the bitcoin dominance value from the command line?
Also, I'm trying to retrieve the value listed on this page https://www.coingecko.com/en/coins/fear-greed-sentiment-set-ii  without success, "cointop price -c greed" doesn't work. Any idea?

Thank you for the extremely useful work you are doing!!!

**Comment by miguelmota** [comment]
The commands `cointop holdings` and `cointop holdings --total` have been added and are available in the latest commit (install with `go get` to try it out).

Here's an example of the output:

![Screenshot from 2020-08-10 01-36-49](https://user-images.githubusercontent.com/168240/89764821-fa300280-daa9-11ea-86a2-fbbf303fcd06.png)

Feedback welcomed :)

**Comment by Emobe** [comment]
Thanks! This is definitely what I was looking for, going to try it out :)

**Comment by Emobe** [comment]
Working perfect thanks.

Is there a way to specify a specific coin's holdings too? e.g `cointop holdings btc` would output bitcoin holdings and balance in fiat? It's okay if not, I could use some filtering with other commands if so

**Comment by miguelmota** [comment]
Not yet but filtering options and output formats (ie csv) will be added this week before publishing a new release

**Comment by miguelmota** [comment]
Hey @wokawoka mind creating a separate issue for those bugs and suggestions to track them separately? thanks!

**Comment by Emobe** [comment]
No worries, does what I wanted to do for now. Thanks for being so quick and I look forward to the filtering!

**Comment by miguelmota** [comment]
Here are examples of some new flags for the holdings command:

Default holdings table view:

```bash
$ cointop holdings
    name        symbol       price      holdings         balance         24h%   %holdings
Bitcoin         BTC       11833.16            10        118331.6        -1.02       74.14
Ethereum        ETH          394.9           100           39490         0.02       24.74
Dogecoin        DOGE    0.00355861        500000          1779.3         1.46        1.11
```

Output to csv:

```bash
$ cointop holdings --format csv
name,symbol,price,holdings,balance,24h%,%holdings
Bitcoin,BTC,11833.16,10,118331.6,-1.02,74.16
Ethereum,ETH,394.48,100,39448,-0.18,24.72
Dogecoin,DOGE,0.00355861,500000,1779.3,1.46,1.12
```

Output to json:

```bash
$ cointop holdings --format json
[{"%holdings":"74.16","24h%":"-1.02","balance":"118331.6","holdings":"10","name":"Bitcoin","price":"11833.16","symbol":"BTC"},{"%holdings":"24.72","24h%":"-0.18","balance":"39448","holdings":"100","name":"Ethereum","price":"394.48","symbol":"ETH"},{"%holdings":"1.12","24h%":"1.46","balance":"1779.3","holdings":"500000","name":"Dogecoin","price":"0.00355861","symbol":"DOGE"}]
```

Human readable numbers (adds comma and dollar signs):

```bash
$ cointop holdings -h
    name        symbol        price     holdings           balance        24h%  %holdings
Bitcoin         BTC      $11,833.16           10        $118,331.6      -1.02%     74.14%
Ethereum        ETH          $394.9          100           $39,490       0.02%     24.74%
Dogecoin        DOGE    $0.00355861      500,000          $1,779.3       1.46%      1.11%
```

Filter coins based on name or symbol:

```bash
$ cointop holdings --filter btc,eth
    name        symbol     price        holdings         balance         24h%   %holdings
Bitcoin         BTC     11833.16              10        118331.6        -1.02       74.16
Ethereum        ETH       394.48             100           39448        -0.18       24.72
```

You can of course combine flags:

```
$ cointop holdings --total --filter btc,doge --format json -h
{"total":"$120,298.37"}
```

For all other options, see help command:

```bash
$ cointop holdings --help
```

**Comment by miguelmota** [comment]
@wokawoka since that token is a low market cap token then looking up by symbol won't work. Try using the coin name slug:

```bash
$ cointop price -c 'fear-greed-sentiment-set-ii'
$238.53
```

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/97facbe48daf2c234203bb886f81fc269ee27f9d, https://github.com/miguelmota/cointop/commit/d8f88d8cf3b73d9186beaa051e569b8d9cac3d7c, https://github.com/miguelmota/cointop/commit/832284dc263dad8b0bb685ed25382e13222ed672, and https://github.com/miguelmota/cointop/commit/261f893c61a0a7687a85c784a69fedcf0e32df4b

**Comment by wokawoka** [comment]
Hey, thank you SO much for implementing the commandline portfolio and dominance features! You really rock!
Sorry for replying so late, the past month has been a kind of hell for me and I had to put everything on pause so that I visited this issue only now.

Just a last question: do you by chance think that it would be possible to include the possibility of adding a fixed amount of euros or dollars to the portfolio? I guess that at the moment that's not possible since we are talking about fiat and euros and dollars are not listed on coingecko, but it would indeed be very useful in many cases (for example when you want to monitor the total amount you reserved to crypto on an exchange).

Thank you again for the extremely useful work you are doing!

**Comment by wokawoka** [comment]
@miguelmota
sorry to bother again, but I'm playing with the "cointop holdings" command; it's really a great feature, but is there by chance the possibility to pass the currency like for single coins with the "-f eur" or "-f usd" parameter?
This would give the possibility to monitor some coins in dollars while getting the total portfolio value in another currency. Probably there's already a way to achieve that in cointop but I'm missing it...
Thank you!

**Comment by miguelmota** [comment]
@wokawoka that's a great suggestion! can you open a new issue with your comments to keep track of it separately? thanks!

@wokawoka the convert flag has been added now which you can try out by updating/installing cointop with go.

Example:

```bash
$ cointop holdings -h --convert eur
    name        symbol    price holdings        balance    24h% %holdings
Ethereum        ETH     €278.49      100        €27,849 -15.87%   100.00%
```

**Comment by wokawoka** [comment]
@miguelmota 

> that's a great suggestion! can you open a new issue with your comments to keep track of it separately? thanks!
I'm going to do it right now! Thanks

> the convert flag has been added now which you can try out by updating/installing cointop with go.
Thank you! You are so fast! I'm looking forward to using this option on the next release (I'm using snap)
