### ISSUE TITLE
When `XDG_CONFIG_HOME` is defined cointop places the config.toml in `$XDG_CONFIG_HOME/.config/cointop`

### ISSUE THREAD

**Issue by biehlerj** [miguelmota/cointop#57]
When a user has defined the environment variable `XDG_CONFIG_HOME`, the expected behavior of programs that use that environment variable is to place their config directory in`$XDG_CONFIG_HOME/<name of app>/`. On first startup of `cointop` it does not follow the expected behavior and instead places its config directory in `$XDG_CONFIG_HOME/.config/cointop/`. This breaks automation scripts that expect the app to properly leverage the environment variable (ex. scripting downloading cointop and placing the color schemes in the `cointop` config directory). 

One way to fix this could be to change `defaultConfigFilePath` call a function that checks if `XDG_CONFIG_HOME` is defined and would either return the expanded value of `$XDG_CONFIG_HOME/cointop/config.toml` or `~/.config/cointop/config.toml` if `XDG_CONFIG_HOME` is not defined.

System Information:

- Ubuntu 18.04
- Go version 1.14.4 linux/amd64

Steps to reproduce:

1. Define the `XDG_CONFIG_HOME` environment variable in your shell's rc file or `$HOME/.profile`
1. Download `cointop` using `go get -u github.com/miguelmota/cointop`
1. Start `cointop` and run `ls -a $XDG_CONFIG_HOME` to verify that `$XDG_CONFIG_HOME` does not contain a `cointop` directory, but does contain a `.config` directory with a `cointop` subdirectory.

**Comment by biehlerj** [comment]
PR submitted for fix #58

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/pull/58
