### ISSUE TITLE
Sorting order is incorrect on startup

### ISSUE THREAD

**Issue by krzko** [miguelmota/cointop#59]
Love the app, but seem to be getting a weird issue with the sorting.

If I restart the app, the default sort order under **rank** is all messaged up. For me to fix it up, I need to do a `cointop reset` and then it works. This has happened on a macOS and Linux host, both installe via `brew`.

See the following screenshot of the sorting issue;

[https://pasteboard.co/JlXcwYy.png](https://pasteboard.co/JlXcwYy.png)

Any ideas?

**Comment by miguelmota** [comment]
Thanks, can confirm that this is a bug. Will get it fixed when I can

**Comment by nsklaus** [comment]
i have the same issue. here, it happens if i change the currency from dollar to euro.
as long as price are in dollar, cointop order stays fine. but if i put prices in euro, then upon restart order is broken. as the first post said, only a `cointop reset` fixes it. but i must do that everytime i want to run cointop.

**Comment by miguelmota** [comment]
In the meantime, you can run `cointop --no-cache` to not use the cache files which seems to be causing the problem

**Comment by nsklaus** [comment]
@miguelmota 
thanks for the workaround while waiting for proper fix, it will be much nicer than reset.

**Comment by miguelmota** [comment]
So the issue was that CoinGecko returns rank `0` for new coins or coins with low activity. A fix has been implemented which pushes coins without a rank to the end of the list. A new release will be out this week. Thanks for the patience

**Comment by githorray** [comment]
Yay! No more `cointop --reset`. Thanks.
