### ISSUE TITLE
Error Installing Snap version in Windows WSL

### ISSUE THREAD

**Issue by ThaBiGGDoGG** [miguelmota/cointop#6]
Ubuntu on Windows 10

error: cannot communicate with server: Post http://localhost/v2/snaps/cointop: dial unix /run/snapd.socket: connect: no such file or directory

**Comment by miguelmota** [comment]
@ThaBiGGDoGG I used pushed a couple fixes. You may try the following

```
snap remove cointop
snap install cointop --stable
```

**Comment by miguelmota** [comment]
Nevermind, still experiencing issue

**Comment by miguelmota** [comment]
@ThaBiGGDoGG Apparently Windows WSL doesn't support `snapd` so installing this snap doesn't seem doable. Here's a thread where WSL and snap support is being discussed https://forum.snapcraft.io/t/windows-subsystem-for-linux/216/16

Closing this issue and adding it to the FAQ
