### ISSUE TITLE
Major issue: Orchid (OXT) coin shows 2 times when added to Portfolio

### ISSUE THREAD

**Issue by readyforaliens** [miguelmota/cointop#63]
Major issue: Orchid (OXT) coin shows 2 times when added to Portfolio

This is very important bug in my opinion as makes app fail show correct data on portfolio.

Here's a picture attachment that demonstrates the bug:

![BugOXT](https://user-images.githubusercontent.com/3072785/91505739-9f334380-e8d0-11ea-8cb6-85ee46ed5050.jpg)

**Comment by miguelmota** [comment]
@readyforaliens can you try running `cointop --no-cache` to see if the coin is still duplicated? trying to debug

**Comment by fuzebox1** [comment]
Had the same problem, but with all coins. After quit and run with --no-cache it was resolved, even when running without --no-cache.

**Comment by readyforaliens** [comment]
When using cointop --no-cache, the OXT (Orchid) coin does not even show up in the list anymore, not able to find it with search function either. Also the OXT based on coinmarketcap is top 300 coins while based on your application is 10000. Also the diagrams at the top of the application are extremely unreliable, they don't show any correct value at the left side. A bit crappy, but good try anyways, still use it ;)

**Comment by miguelmota** [comment]
cointop uses coingecko by default and coingecko doesn't have a rank for OXT for whatever reason (see screenshot). It's N/A which means the api returns as rank `0` and cointop will push any rank `0` (N/A) coins to the end of the list.

![Screenshot from 2020-08-30 20-57-42](https://user-images.githubusercontent.com/168240/91681499-82328680-eb03-11ea-86f6-616913c8f2d2.png)

https://www.coingecko.com/en/coins/orchid-protocol

When running cointop without cache, it will take a minute or two for all the coins to be fetched. In the case of coingecko then OXT might be in the pages at the very end. 

Not sure why it was duplicated but will keep looking into it.

@readyforaliens i agree, the charts need some more love 🙂 

Always happy to accept PRs

**Comment by miguelmota** [comment]
Closing since it should have been fixed but please re-open of problem persists.
