### ISSUE TITLE
Cannot set portfolio value for ETH and BTC, only for others.

### ISSUE THREAD

**Issue by fuzebox1** [miguelmota/cointop#64]
I was able to set the portfolio values for several altcoins, but when it came to ETH and BTC it wouldn't "stick".
I was able to set them manually in the config file however. In there they where both set as 0.0, even after editing inside cointop.
Now i am able to change the portfolio values from inside cointop as i would assume it should function.

**Comment by miguelmota** [comment]
Issue should be fixed now. Closing, but create another issue if experiencing problems.
