### ISSUE TITLE
(enhancement) Shortcut to open the coingecko coin page in default browser 

### ISSUE THREAD

**Issue by wokawoka** [miguelmota/cointop#66]
Just an idea:
I believe that being able to launch the corresponding coingecko coin page in the browser via a shortcut would be extremely useful. 
The cointop built-in graph in the terminal is very useful but very often I feel the need to quickly open up a proper graph in the browser.
I'm not sure if that would be easy to implement or even technically achievable tough...

**Comment by vuongggggg** [comment]
Hi, may I ask about your idea: How is it going different from shift+o now?

**Comment by wokawoka** [comment]
Sorry, I noticed your message only now. 
Is shift+o supposed to open up the coingecko page of the selected coin in the browser?

**Comment by vuon9** [comment]
Based on the code, I think it has. But just didn't support default CMD and Powershell yet.
Can also take a look at this: `D:\go\src\github.com\miguelmota\cointop\cointop\common\open\open.go`
![image](https://user-images.githubusercontent.com/3168632/98685767-5bfa5400-239a-11eb-9249-28afb70122b0.png)

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/pull/77

**Comment by wokawoka** [comment]
great! 
but still I can't understand how I am supposed to launch the page on the browser from the cointop interface in the command line. Should I click on the coin line? Is there a shortcut? I'm sorry but I couldn't find the correct way (I'm on linux/kde).
Thanks!

**Comment by miguelmota** [comment]
@wokawoka pressing the letter key <kbd>o</kbd> opens up the coingecko link in the browser as long as you have one of these commands available in your system:  `xdg-open`, `gvfs-open`. `gnome-open`, `kde-open`, `exo-open`, `enlightenment_open`, `open`. Do any of these work? maybe you don't have a default browser configured? which can be set with `xdg-settings set default-web-browser firefox.desktop`

**Comment by wokawoka** [comment]
Sorry for the late reply! (I check github only from time to time)
Unfortunately pressing the letter key "o" doesn't open the coingecko page here.
I'm running kde here, "kde-open" doesn't work but "kde-open5" or "xdg-open" followed by a website address correctly open the default browser pointing to the correct page.
Is there something I could do to "fix" the problem?
Thank you!

**Comment by miguelmota** [comment]
@wokawoka `xdg-open` should have worked so not really sure. Just added `kde-open5` to list of possible commands so you can try re-installing with Go to see if that helps! By any chance are you using zsh instead of bash? trying to replicate the problem

**Comment by wokawoka** [comment]
Unfortunately I'm just using the snap release and I guess that reinstalling with go would be too complicated. I'm using regular bash.
Thank you!
