### ISSUE TITLE
cointop windows width problem (too narrow)

### ISSUE THREAD

**Issue by sinepgnol** [miguelmota/cointop#68]
Hello,

after running cointop, its window is always this narrow (picture below), regardless of my Terminal window width. However, in the official cointop GitHub picture its window is much wider, occupying the entire Terminal window width.
mine:
<img width="2670" alt="Screenshot 2020-09-13 at 21 20 45" src="https://user-images.githubusercontent.com/45313882/93026657-03ac0d80-f608-11ea-800c-33e1a7f40775.png">

official cointop GitHub picture:
https://user-images.githubusercontent.com/168240/39569578-7ce9f3b6-4e7a-11e8-82a9-8a18b91b1bd5.png

What could be the problem?

**Comment by miguelmota** [comment]
Hi @sinepgnol, can you provide the following details:

- your OS
- which terminal you're using
- how you installed cointop

It would help me in debugging. Thanks

**Comment by sinepgnol** [comment]
- my OS: macOS Catalina 10.15.6
- I'm using Apple's default built-in app called Terminal with zsh shell.
- I installed cointop via Homebrew

**Comment by miguelmota** [comment]
Can't seem to reproduce this. Very strange that it would be cut off like that.
