### ISSUE TITLE
"not enough data for chart" whith coinmarketcap api

### ISSUE THREAD

**Issue by sinepgnol** [miguelmota/cointop#69]
<img width="1354" alt="Screenshot 2020-09-14 at 14 23 49" src="https://user-images.githubusercontent.com/45313882/93085640-25ec6c80-f696-11ea-94c7-eacdbd5c20c9.png">
- my OS: macOS Catalina 10.15.6
- I'm using Apple's default built-in app called Terminal with zsh shell.
- I installed cointop via Homebrew

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/295f163ae24e8bde849f72bfdf7b604234b4691e
