### ISSUE TITLE
Weird [?] For Price Charts Lines

### ISSUE THREAD

**Issue by ThaBiGGDoGG** [miguelmota/cointop#7]
![screenshot 114](https://user-images.githubusercontent.com/38387853/38912612-49749f0e-42a4-11e8-983b-3fe8025e0eda.png)

Just got this installed & it is putting [?] for the price charts. Everything else seems to be working ok for me.

**Comment by miguelmota** [comment]
I'm not familiar with windows WSL but can you try using a different font and make sure to use UTF-8 encoding for the terminal emulator?

**Comment by miguelmota** [comment]
@ThaBiGGDoGG which font are you using? I think Consolas doesn't support certain characters. See this help guide https://github.com/aksakalli/gtop/wiki/Windows-Command-Prompt-Font-Support and report back if you got the fonts working

**Comment by miguelmota** [comment]
@ThaBiGGDoGG awesome! I've added it to the [wiki](https://github.com/miguelmota/cointop/wiki)
