### ISSUE TITLE
can't build on Windows 10

### ISSUE THREAD

**Issue by vuongggggg** [miguelmota/cointop#70]
```pws
PS C:\Users\vuong> go get -u github.com/miguelmota/cointop
package github.com/miguelmota/cointop/cointop/ssh: build constraints exclude all Go files in D:\workspace\go\src\github.com\miguelmota\cointop\cointop\ssh
```
I got this error when try to install cointop on Windows 10 (Powershell/Git bash). How could I do to resolve this issue?

Thanks.

====
Update:

After having an investigation, I see the `ServerCmd()` in `cointop\cmd\server.go` couldn't be running in Windows because the `github.com/creack/pty` still not support Windows yet.

I can make it build by disable `ServerCmd()` but not sure about the purpose of `ServerCmd()`, can I ask for an explanation, please? 😂

**Comment by miguelmota** [comment]
@vuongggggg the server allows you to use cointop remotely. 

For example, try:

```bash
ssh cointop.sh
```

In that example the remote server, cointop.sh, is running the cointop SSH server.

More information is in the [README](https://github.com/miguelmota/cointop#ssh-server)

**Comment by vuongggggg** [comment]
Thanks @miguelmota!
