### ISSUE TITLE
unable to start cointop - lookup graphs2.coinmarketcap.com: no such host

### ISSUE THREAD

**Issue by githorray** [miguelmota/cointop#74]
error:

`Get https://graphs2.coinmarketcap.com/global/marketcap-total/1603082022000/1603686822000: dial tcp: lookup graphs2.coinmarketcap.com: no such host`

Maybe a DNS issue?

https://www.digwebinterface.com/?hostnames=graphs2.coinmarketcap.com&ns=all

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/295f163ae24e8bde849f72bfdf7b604234b4691e
