### ISSUE TITLE
Please consider submitting an RPM build via COPR

### ISSUE THREAD

**Issue by sadsfae** [miguelmota/cointop#8]
Thanks for working on this, it looks awesome.  Could you please consider making it available [as a Flatpak](https://github.com/flathub/flathub/wiki/App-Submission) as it's a much better improvement to snap packages which seem to be Ubuntu-only.

Would you also consider publishing an RPM format [via COPR](https://docs.pagure.org/copr.copr/user_documentation.html)?

**Comment by miguelmota** [comment]
will do!

**Comment by miguelmota** [comment]
Submitted cointop to flathub https://github.com/flathub/flathub/pull/387

**Comment by miguelmota** [comment]
here are the steps to install cointop using my flatpak repo

Add the flathub repository (if not done so already)

```bash
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

Install the freedesktop runtime (if not done so already)

```bash
sudo flatpak install flathub org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6
```

Add the cointop flatpak repo

```bash
flatpak --user remote-add --if-not-exists --no-gpg-verify cointop https://cointop.sh/cointop.flatpakrepo
```

Install cointop flatpak

```bash
flatpak --user install cointop com.github.miguelmota.Cointop
```

Run cointop flatpak

```bash
flatpak run com.github.miguelmota.Cointop
```

**Comment by miguelmota** [comment]
cointop is now available on [copr](https://copr.fedorainfracloud.org/coprs/miguelmota/cointop/) for Fedora

Enable repository

```bash
sudo dnf copr enable miguelmota/cointop
```

Install cointop

```bash
sudo dnf install cointop
```
