### ISSUE TITLE
Config is not in ~/.config/cointop

### ISSUE THREAD

**Issue by calgara12** [miguelmota/cointop#82]
My config file is stored in/tmp/cointop_config

In my ~/.config/cointop is only a folder named "color" It cointains a config.toml, but that only looks to save the color settings.
My favourites and portfolio are saved in the /tmp/ folder. In the docs it says that the default 

I am using a docker install.
This is how i started my container: docker run -p 2222:22 -v ~/.ssh:/keys --entrypoint cointop -it cointop/cointop server -k /keys/id_rsa

Thanks in advance :)

**Comment by GETandSELECT** [comment]
see also https://github.com/miguelmota/cointop/issues/85 with the same or similar issue

**Comment by miguelmota** [comment]
If using docker then the host config directory will need to be mounted on the container; i.e. `-v ~/.config/cointop:/tmp/cointop_config`

Full command:

```bash
docker run -p 2222:22 -v ~/.ssh:/keys -v ~/.config/cointop:/tmp/cointop_config --entrypoint cointop -it cointop/cointop server -k /keys/id_rsa
```

Updated instructions on [docs.cointop.sh/ssh](https://docs.cointop.sh/ssh/)
