### ISSUE TITLE
Please can you create Appimage file?

### ISSUE THREAD

**Issue by re42** [miguelmota/cointop#83]
I would really appreciate it if you can create appimage ready-made binaries.

Firstly i tried installing on Ubuntu 18.04 with the install file:
`curl -o- https://raw.githubusercontent.com/miguelmota/cointop/master/install.sh | bash`
and it constantly gives error:
`cointop: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32 not found (required by cointop)`
There doesnt seem to be a way to install GLIB v2.32 on Ubuntu 18.04 without screwing up everything else on my system that depends on current version of GLIBC.

I am also not a fan of using snap installations at all.

If its possible and if you have some time, could you be able to compile the install file in an appimage?  It would be so much easier and simpler.
Otherwise i wont be able to use cointop :(
I would highly appreciate this.

thank you kindly.

**Comment by miguelmota** [comment]
@re42 That's a great suggestion! an AppImage would be very useful indeed :)

I'll read up on it and let you know when a generated AppImage is available for download

**Comment by miguelmota** [comment]
Good news!

You can download the AppImage from the [releases](https://github.com/miguelmota/cointop/releases) page.

```bash
VERSION="v$(curl --silent "https://api.github.com/repos/miguelmota/cointop/releases/latest" | grep -Po --color=never '"tag_name": ".\K.*?(?=")')"
URL="https://github.com/miguelmota/cointop/releases/download/$VERSION/cointop-$VERSION.glibc2.32-x86_64.AppImage"
wget $URL
```

Make AppImage executable:

```bash
chmod +x cointop-*.AppImage
```

Run AppImage:

```bash
./cointop-*.AppImage
```
