### ISSUE TITLE
Duplicate Entries in Favorites and Portfolio

### ISSUE THREAD

**Issue by calgara12** [miguelmota/cointop#84]
Suddenly i have duplicate entries for all my favourites, even though they show up only once in the config file.
And it has been working for a few days, but today the duplicate entries show up.

I'm using the docker image.
https://imgur.com/a/q5f3bWL

Thanks in advance

**Comment by miguelmota** [comment]
Hey @calgara12, thanks for the bug report. Can you try `docker pull cointop/cointop` and re-running? Just updated the docker image which includes a couple of bug fixes.

**Comment by calgara12** [comment]
Just tried it and it seems to be fixed. Thanks

**Comment by clayt0nk** [comment]
Will this be pushed to flatpak soon? I am seeing the same behavior

**Comment by miguelmota** [comment]
@clayt0nk flatpak should now be up-to-date

https://github.com/flathub/com.github.miguelmota.Cointop

Thanks for reporting the issue
