### ISSUE TITLE
Ability to input negative balances

### ISSUE THREAD

**Issue by HPaulson** [miguelmota/cointop#87]
## Proposal
In the portfolio section, it would be nice if users had the ability to add a negative balance for a coin. Such a feature would be extremely simple to implement by allowing users to input a negative value in the portfolio balance box, and adding the negative value (Subtracting the amount) from the total value.

## Why?
Although this feature may seem quite peculiar- it actually has a very distinct and useful purpose for a large group of traders. Many crypto traders, especially those new to the space, engage in Leverage or Margin trading. Such trading allows a user to borrow crypto, often in the form of a stablecoin, from an exchange. Then traders can then trade and invest the borrowed crypto, and pay their debt back in interest after a certain interval. This type of trading allows for more profits while having less cash to invest. Due to this, leverage and margin investors will often carry a negative balance in debt of a stablecoin, such as USDT, and have said debt invested in other coins. Having the ability to input this debt in the form of a negative value would be extremely useful for showing a trader their *actual* profits and balance, which would exclude their debt.

Thanks for any consideration,
Hunter

**Comment by miguelmota** [comment]
@HPaulson not opposed to this! Will allow for negative holdings input in the next minor release : )

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/3aed9846fef7c25eb7d9cbf22aa8178930c300b5
