### ISSUE TITLE
How to bind semicolon ";" as a shortcut

### ISSUE THREAD

**Issue by nostdm** [miguelmota/cointop#89]
I've tried to remap the shortuct for `next_page` from `l` to `";"` but it doesn't work.

I've tried multiple definitions:

```
  ; = "next_page"
  ";" = "next_page"
  semicolon = "next_page"
```
Given that none of them work, how would I go about binding the semicolon key to the `next_page` command?

**Comment by miguelmota** [comment]
This should work:

```
  ";" = "next_page"
```

What OS are you on?

**Comment by nostdm** [comment]
```
$ cointop --version
v1.6.0
$ uname -a
Linux desktop 5.10.16-arch1-1 #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000 x86_64 GNU/Linux
```

**Comment by miguelmota** [comment]
@nostdm interesting, I think you are correct. I see the bug now in the cointop code. Will get this fixed in the next patch release. Thanks!

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/296c67e6fdefecedecc0020678e8ec9bb57f4447
