### ISSUE TITLE
Is it possible to remove the empty line at the top when using --only-table mode

### ISSUE THREAD

**Issue by nostdm** [miguelmota/cointop#90]
When the marketbar and chart are hidden there's an empty line at the top above the table header. Is this intentional and/or is there a way to remove that line so that the table header starts at the top of the terminal window? Screenshot of empty line:

![Empty Line](https://user-images.githubusercontent.com/16334589/108012379-200e0500-7001-11eb-99d3-8dc495f4ef3b.png)

Update: In fact it seems that the empty line is there regardless of whether the chart and marketbar is hidden.

**Comment by miguelmota** [comment]
Will get this fixed in the next patch release.

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/0576b043d4f352abe65f8f87d02e8e0f9837af1e
