### ISSUE TITLE
No background transparency (built from source)

### ISSUE THREAD

**Issue by caduz** [miguelmota/cointop#95]
Hi, 

I've built cointop from source and the background transparency is not working (I'm using cointop color scheme). I'm not sure if I'm missing any dependency or if I built it with wrong flags. My go version is go1.15.8 linux/amd64.

Steps I took to build from source:
1. Cloned the cointop repo
2. Ran go build 

I've got no errors and now I just run the `main` file. Apart from the transparency, everything else works flawlessly. Does anyone know how can I fix that?

**Comment by miguelmota** [comment]
@caduz the default background color is `black`. To make it use the system default, fork the [colorscheme](https://github.com/cointop-sh/colors/blob/7a371aab14d1364afde00c7f35bb76630b0b0bce/cointop.toml#L4) and change it to:

```bash
base_bg = "default"
```
