### ISSUE TITLE
Won't run on Raspberry Pi using Snapd, GO or Full Dist download

### ISSUE THREAD

**Issue by lurchinms** [miguelmota/cointop#97]
![cointop](https://user-images.githubusercontent.com/12227665/110420120-46531d80-8060-11eb-976c-930e0a581fb6.jpg)

**Comment by miguelmota** [comment]
@lurchinms to confirm, that is using the latest code correct?  it's interesting because that endpoint was switched out for the newer one a few weeks ago so I wouldn't expect to see it

```
go get -u github.com/miguelmota/cointop
```

**Comment by lurchinms** [comment]
Same thing. I even load Ubunto Server 20.04 on this Raspberry Pi and it won'y run.

**Comment by lurchinms** [comment]
I used snapd to install Go --classic 
go version go1.15.8 linux/arm64

**Comment by lurchinms** [comment]
I got it. Had to run using ~/go/bin/cointop
